# Generated by Django 4.2.13 on 2024-07-01 03:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dalton', '0002_alter_accountuser_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('9ab2746f-485d-4b2b-9e6d-3e740823868b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
